/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { OrdersResponse } from '../../models/orders-response';

export interface GetOrders$Params {

/**
 * Флаг для искусственного вызова ошибки (для тестов)
 */
  fail?: boolean;

/**
 * Флаг для искусственного вызова 401 ошибки (для тестов)
 */
  authFail?: boolean;
}

export function getOrders(http: HttpClient, rootUrl: string, params?: GetOrders$Params, context?: HttpContext): Observable<StrictHttpResponse<OrdersResponse>> {
  const rb = new RequestBuilder(rootUrl, getOrders.PATH, 'get');
  if (params) {
    rb.query('fail', params.fail, {});
    rb.query('authFail', params.authFail, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<OrdersResponse>;
    })
  );
}

getOrders.PATH = '/orders';
