/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { createOrder } from '../fn/orders/create-order';
import { CreateOrder$Params } from '../fn/orders/create-order';
import { getOrders } from '../fn/orders/get-orders';
import { GetOrders$Params } from '../fn/orders/get-orders';
import { OrderDto } from '../models/order-dto';
import { OrdersResponse } from '../models/orders-response';


/**
 * Операции с заказами
 */
@Injectable({ providedIn: 'root' })
export class OrdersService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getOrders()` */
  static readonly GetOrdersPath = '/orders';

  /**
   * Получить список заказов (сделок).
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getOrders()` instead.
   *
   * This method doesn't expect any request body.
   */
  getOrders$Response(params?: GetOrders$Params, context?: HttpContext): Observable<StrictHttpResponse<OrdersResponse>> {
    const obs = getOrders(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Получить список заказов (сделок).
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getOrders$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getOrders(params?: GetOrders$Params, context?: HttpContext): Observable<OrdersResponse> {
    const resp = this.getOrders$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<OrdersResponse>): OrdersResponse => r.body)
    );
  }

  /** Path part for operation `createOrder()` */
  static readonly CreateOrderPath = '/orders';

  /**
   * Создать новый заказ.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createOrder()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createOrder$Response(params: CreateOrder$Params, context?: HttpContext): Observable<StrictHttpResponse<OrderDto>> {
    const obs = createOrder(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Создать новый заказ.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createOrder$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createOrder(params: CreateOrder$Params, context?: HttpContext): Observable<OrderDto> {
    const resp = this.createOrder$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<OrderDto>): OrderDto => r.body)
    );
  }

}
