/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CompanyDto } from '../models/company-dto';
import { FinancialsDto } from '../models/financials-dto';
export interface OrderDto {
  company: CompanyDto;
  financials: FinancialsDto;
  transaction_id: number;
  workflow_state: 'NEW' | 'DONE' | 'IN_PROGRESS' | 'CANCELLED';
}
