/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { OrderDto } from '../models/order-dto';
import { OrderPagination } from '../models/order-pagination';
export interface OrdersResponse {
  items: Array<OrderDto>;
  pagination: OrderPagination;
}
