/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UserDto {
  access_role: 'admin' | 'manager' | 'user';
  first_name: string;
  is_active: boolean;
  last_login: string;
  last_name: string;
  user_internal_id: number;
}
