/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { UserDto } from '../models/user-dto';
import { UsersMeta } from '../models/users-meta';
export interface UsersResponse {
  data: Array<UserDto>;
  meta: UsersMeta;
}
