/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UsersResponse } from '../../models/users-response';

export interface GetUsers$Params {

/**
 * Часть имени для поиска
 */
  name?: string;

/**
 * Фильтр по роли
 */
  role?: string;

/**
 * Флаг для искусственного вызова ошибки (для тестов)
 */
  fail?: boolean;

/**
 * Флаг для искусственного вызова 401 ошибки (для тестов)
 */
  authFail?: boolean;
}

export function getUsers(http: HttpClient, rootUrl: string, params?: GetUsers$Params, context?: HttpContext): Observable<StrictHttpResponse<UsersResponse>> {
  const rb = new RequestBuilder(rootUrl, getUsers.PATH, 'get');
  if (params) {
    rb.query('name', params.name, {});
    rb.query('role', params.role, {});
    rb.query('fail', params.fail, {});
    rb.query('authFail', params.authFail, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<UsersResponse>;
    })
  );
}

getUsers.PATH = '/users';
